services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./fronted
    env_file:
      - ./fronted/.env
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
