export const USER_REPOSITORY = Symbol("USER_REPOSITORY");
export const ACCOUNT_REPOSITORY = Symbol("ACCOUNT_REPOSITORY");
export const TRANSACTION_REPOSITORY = Symbol("TRANSACTION_REPOSITORY");
export const PASSWORD_HASHER = Symbol("PASSWORD_HASHER");
export const TOKEN_SERVICE = Symbol("TOKEN_SERVICE");
export const IDEMPOTENCY_STORE = Symbol("IDEMPOTENCY_STORE");
export const DOMAIN_EVENT_PUBLISHER = Symbol("DOMAIN_EVENT_PUBLISHER");
